# Generated by Django 4.2.19 on 2025-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabeli', '0002_remove_contact_email_contact_name_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Complaint', 'Complaint'), ('Suggestion', 'Suggestion')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
