# Generated by Django 4.2.19 on 2025-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabeli', '0003_remove_contact_phone_contact_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
